import { User, UserCheck } from "lucide-react"

import { customerSchema } from "./types/customer-types"

export const genders = [
  {
    value: "male",
    label: "Nam",
    icon: User,
  },
  {
    value: "female",
    label: "Nữ",
    icon: UserCheck,
  },
]

const customersData = [
  {
    id: "CUS-1001",
    name: "Nguyễn Văn An",
    phone: "0901234567",
    email: "nguyenvanan@gmail.com",
    address: "123 Nguyễn Huệ, Quận 1, TP.HCM",
    gender: "male",
    occupation: "Kỹ sư phần mềm",
    notes: "Khách hàng VIP, thường xuyên sử dụng dịch vụ premium.",
  },
  {
    id: "CUS-1002",
    name: "Trần Thị Bích",
    phone: "0912345678",
    email: "tranthibich@gmail.com",
    address: "456 Lê Lợi, Quận 3, TP.HCM",
    gender: "female",
    occupation: "Giáo viên",
    notes: "",
  },
  {
    id: "CUS-1003",
    name: "Lê Hoàng Cường",
    phone: "0923456789",
    email: "lehoangcuong@gmail.com",
    address: "789 Trần Hưng Đạo, Quận 5, TP.HCM",
    gender: "male",
    occupation: "Bác sĩ",
    notes: "Cần tư vấn thêm về gói dịch vụ cao cấp.",
  },
  {
    id: "CUS-1004",
    name: "Phạm Thị Dung",
    phone: "0934567890",
    email: "phamthidung@gmail.com",
    address: "101 Võ Văn Tần, Quận 3, TP.HCM",
    gender: "female",
    occupation: "Nhà thiết kế",
    notes: "Quan tâm đến sản phẩm thiết kế nội thất.",
  },
  {
    id: "CUS-1005",
    name: "Hoàng Minh Đức",
    phone: "0945678901",
    email: "hoangminhduc@gmail.com",
    address: "202 Hai Bà Trưng, Quận 1, TP.HCM",
    gender: "male",
    occupation: "Doanh nhân",
    notes: "Khách hàng doanh nghiệp, mua sỉ số lượng lớn.",
  },
  {
    id: "CUS-1006",
    name: "Vũ Thị Hoa",
    phone: "0956789012",
    email: "vuthihoa@gmail.com",
    address: "303 Pasteur, Quận 1, TP.HCM",
    gender: "female",
    occupation: "Kế toán",
    notes: "",
  },
  {
    id: "CUS-1007",
    name: "Đặng Quốc Hùng",
    phone: "0967890123",
    email: "dangquochung@gmail.com",
    address: "404 Điện Biên Phủ, Quận Bình Thạnh, TP.HCM",
    gender: "male",
    occupation: "Luật sư",
    notes: "Hỗ trợ pháp lý cho nhiều dự án.",
  },
  {
    id: "CUS-1008",
    name: "Ngô Thị Kim",
    phone: "0978901234",
    email: "ngothikim@gmail.com",
    address: "505 Cách Mạng Tháng 8, Quận 10, TP.HCM",
    gender: "female",
    occupation: "Dược sĩ",
    notes: "Khách hàng mới, được giới thiệu từ CUS-1003.",
  },
  {
    id: "CUS-1009",
    name: "Bùi Thanh Long",
    phone: "0989012345",
    email: "buithanhlong@gmail.com",
    address: "606 Nguyễn Thị Minh Khai, Quận 3, TP.HCM",
    gender: "male",
    occupation: "Kiến trúc sư",
    notes: "",
  },
  {
    id: "CUS-1010",
    name: "Lý Thị Mai",
    phone: "0990123456",
    email: "lythimai@gmail.com",
    address: "707 Lý Tự Trọng, Quận 1, TP.HCM",
    gender: "female",
    occupation: "Marketing Manager",
    notes: "Đối tác chiến lược, cần chăm sóc đặc biệt.",
  },
  {
    id: "CUS-1011",
    name: "Trịnh Văn Nam",
    phone: "0901122334",
    email: "trinhvannam@gmail.com",
    address: "808 Nguyễn Đình Chiểu, Quận 3, TP.HCM",
    gender: "male",
    occupation: "Lập trình viên",
    notes: "Quan tâm đến giải pháp công nghệ mới.",
  },
  {
    id: "CUS-1012",
    name: "Đỗ Thị Oanh",
    phone: "0912233445",
    email: "dothioanh@gmail.com",
    address: "909 Phạm Ngọc Thạch, Quận 3, TP.HCM",
    gender: "female",
    occupation: "Giám đốc",
    notes: "Khách hàng VIP, ưu tiên xử lý nhanh.",
  },
  {
    id: "CUS-1013",
    name: "Phan Quốc Phong",
    phone: "0923344556",
    email: "phanquocphong@gmail.com",
    address: "111 Lê Văn Sỹ, Quận Phú Nhuận, TP.HCM",
    gender: "male",
    occupation: "Nhiếp ảnh gia",
    notes: "",
  },
  {
    id: "CUS-1014",
    name: "Mai Thị Quỳnh",
    phone: "0934455667",
    email: "maithiquynh@gmail.com",
    address: "222 Nguyễn Văn Trỗi, Quận Phú Nhuận, TP.HCM",
    gender: "female",
    occupation: "Nhà báo",
    notes: "Cần cập nhật thông tin liên hệ mới.",
  },
  {
    id: "CUS-1015",
    name: "Cao Minh Tuấn",
    phone: "0945566778",
    email: "caominhtuan@gmail.com",
    address: "333 Hoàng Văn Thụ, Quận Tân Bình, TP.HCM",
    gender: "male",
    occupation: "Phi công",
    notes: "Lịch làm việc không cố định, liên hệ qua email.",
  },
]

export const customerMockData = customerSchema.array().parse(customersData)
